title: <p align="center"> Prachi Goliwadekar  </p>
logo: /assets/img/Photo.jpeg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="www.linkedin.com/in/prachi-goliwadekar-88321822">LinkedIn</a> |
  <a href="https://github.com/prachigoliwadekar">GitHub</a>
  
  <br>   
  Seasoned IT professional with more than 15 years of experience in management and developing business solutions on web platforms.<br/>
  Last 9 years, I have been working in Microsoft technologies that includes 4 years in .NET Core and 9 years in ASP.NET MVC.
  <br>
  </p>



theme: jekyll-theme-minimal
